/**:
  ros__parameters:
    K: [ -1.000000, -3.388414, -94.580966, -12.299571]

    ke: 0.1
    kv: 1.0
    kx: 10.0
    kdelta: 1.0

    # 0.0 angle - upward position. When absolute angle is less than this threshold
    # transition from swing up to LQR
    lqr_transition_angle: 30.0
    initial_force: 0.5
    rviz_test: false
   
# K_ = Eigen::Vector4d(this->get_parameter("K").as_double_array().data());
# ke_ = this->get_parameter("ke").as_double();
# kv_ = this->get_parameter("kv").as_double();
# kx_ = this->get_parameter("kx").as_double();
# kdelta_ = this->get_parameter("kdelta").as_double();
# lqr_transition_angle_ = this->get_parameter("lqr_transition_angle").as_double();